# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_short',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
